# Generated by Django 3.0.3 on 2020-02-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitySort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
                ('aqi', models.IntegerField()),
                ('pm25', models.IntegerField()),
                ('pm10', models.IntegerField()),
                ('co', models.FloatField(max_length=5)),
                ('no2', models.IntegerField()),
                ('o31h', models.IntegerField()),
                ('o38h', models.IntegerField()),
                ('so2', models.IntegerField()),
            ],
            options={
                'db_table': 'city_sort',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(db_index=True, max_length=20)),
                ('aqi', models.IntegerField()),
                ('pm25', models.IntegerField()),
                ('pm10', models.IntegerField()),
                ('co', models.FloatField(max_length=5)),
                ('no2', models.IntegerField()),
                ('o31h', models.IntegerField()),
                ('o38h', models.IntegerField()),
                ('so2', models.IntegerField()),
                ('record_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(db_index=True, max_length=20, unique=True)),
                ('city_name_eng', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
        ),
    ]
